// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.example.account/com.example.account.proto

package com.example.account;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string brand = 2;</code>
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 2;</code>
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>int32 agency = 3;</code>
   */
  int getAgency();

  /**
   * <code>int32 number = 4;</code>
   */
  int getNumber();

  /**
   * <code>int32 digit = 5;</code>
   */
  int getDigit();
}
