// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.example.account/com.example.account.proto

package com.example.account;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
